// export const FETCHING_MOVIES_REQUEST = "FETCHING_MOVIES_REQUEST";

// export const MOVIES_UPCOMING = "MOVIES_UPCOMING";

export const POST_MDB_CONFIG = "POST_MDB_CONFIG";
export const POST_MOVIES_UPCOMING = "POST_MOVIES_UPCOMING";
